[package]
name = "r2d2_freetds"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8"
freetds = { git = "https://github.com/degaart/freetds-rs.git" }

